### ISSUE TITLE
[coc.nvim] Error on InsertEnter: request error nvim_buf_clear_namespace - Invalid buffer id

### ISSUE THREAD

**Issue by Innei** [neoclide/coc-git#86] opened 2020-02-23 09:00 UTC
If I set `git.addGBlameToVirtualText = true`, sometime it cause an error. Like this: 
![image](https://user-images.githubusercontent.com/41265413/75109423-c1b47d80-565d-11ea-86ad-17bf9c87f0a4.png)
Such as toggle `coc-explorer` or `undo a hunk`.
Is my config wrong?

```json
{
  "npm.binPath": "yarn",
  "coc.preferences.hoverTarget": "echo",
  "coc.preferences.formatOnInsertLeave": true,
  "coc.preferences.enableFloatHighlight": true,
  "coc.preferences.snippetStatusText": "Ⓢ ",
  "coc.preferences.extensionUpdateCheck": "weekly",
  "coc.preferences.currentFunctionSymbolAutoUpdate": true,
  "suggest.detailMaxLength": 100,
  "suggest.noselect": true,
  "suggest.enablePreselect": false,
  "suggest.triggerAfterInsertEnter": false,
  "suggest.timeout": 5000,
  "suggest.enablePreview": true,
  "suggest.floatEnable": true,
  "suggest.detailField": "preview",
  "suggest.snippetIndicator": "*",
  "suggest.triggerCompletionWait": 100,
  "suggest.echodocSupport": true,
  "suggest.completionItemKindLabels": {
    "class": "\uf0e8",
    "color": "\ue22b",
    "constant": "\uf8fe",
    "default": "\uf29c",
    "enum": "\uf435",
    "enumMember": "\uf02b",
    "event": "\ufacd",
    "field": "\uf93d",
    "file": "\uf723",
    "folder": "\uf115",
    "function": "\u0192",
    "interface": "\uf417",
    "keyword": "\uf1de",
    "method": "\uf6a6",
    "module": "\uf40d",
    "operator": "\uf915",
    "property": "\ue624",
    "reference": "\ufa46",
    "snippet": "\ue60b",
    "struct": "\ufb44",
    "text": "\ue612",
    "typeParameter": "\uf728",
    "unit": "\uf475",
    "value": "\uf89f",
    "variable": "\ue71b"
  },
  "diagnostic.signOffset": 1,
  "diagnostic.errorSign": "×",
  "diagnostic.warningSign": "»",
  "diagnostic.infoSign": "ღ",
  "diagnostic.hintSign": "ஐ",
  "diagnostic.displayByAle": false,
  "diagnostic.refreshOnInsertMode": true,
  "diagnostic.refreshAfterSave": false,
  "diagnostic.checkCurrentLine": true,
  "diagnostic.virtualTextPrefix": "                        => ",
  "diagnostic.virtualText": true,
  "codeLens.enable": true,
  "list.previewHighlightGroup": "Statement",
  "list.nextKeymap": "<C-e>",
  "list.previousKeymap": "<C-u>",
  "coc.preferences.jumpCommand": "tab drop",
  "coc.preferences.formatOnSaveFiletypes": [
    "python",
    "css",
    "javascript",
    "typescript",
    "vue"
  ],
  "prettier.eslintIntegration": true,
  "prettier.disableLanguages": [],
  "signature.target": "echo",
  "signature.enable": true,
  "yank.enableCompletion": false,
  "explorer.width": 38,
  "explorer.quitOnOpen": true,
  "explorer.sources": [
    {
      "name": "buffer",
      "expand": true
    },
    {
      "name": "file",
      "expand": true
    }
  ],
  "explorer.file.column.indent.indentLine": true,
  "explorer.file.showHiddenFiles": true,
  "explorer.icon.enableNerdfont": true,
  "explorer.file.column.git.showIgnored": true,
  "explorer.keyMappingMode": "none",
  "explorer.keyMappings": {
    "u": "nodePrev",
    "e": "nodeNext",

    "*": "toggleSelection",
    "<tab>": "actionMenu",

    "n": "expandOrCollapse",
    "E": ["toggleSelection", "normal:j"],
    "U": ["toggleSelection", "normal:k"],
    "gl": "expandRecursive",
    "gh": "collapseRecursive",
    "i": "expand",
    "<cr>": "open",
    "s": "openInVsplit",
    "o": "openInTab",
    "<bs>": "gotoParent",
    "l": "gotoParent",

    "yp": "copyFilepath",
    "yn": "copyFilename",
    "yy": "copyFile",
    "dd": "cutFile",
    "pp": "pasteFile",
    "dD": "delete",
    "Dd": "deleteForever",

    "a": "addFile",
    "k": "addFile",
    "M": "addDirectory",
    "cw": "rename",

    ".": "toggleHidden",
    "zh": "toggleHidden",
    "R": "refresh",

    "?": "help",
    "q": "quit",
    "X": "systemExecute",
    "gd": "listDrive",

    "f": "search",
    "F": "searchRecursive",

    "B": "gotoSource:file",
    "b": "gotoSource:buffer",

    "[[": "sourcePrev",
    "]]": "sourceNext",

    "[d": "diagnosticPrev",
    "]d": "diagnosticNext",

    "[c": "gitPrev",
    "]c": "gitNext",
    "<<": "gitStage",
    ">>": "gitUnstage"
  },
  "git.enableGutters": true,
  "git.branchCharacter": "\uf408",
  "git.addGBlameToBufferVar": false,
  "git.addGBlameToVirtualText": true,
  "git.virtualTextPrefix": "                 ~ ",
  "git.addedSign.hlGroup": "GitGutterAdd",
  "git.changedSign.hlGroup": "GitGutterChange",
  "git.removedSign.hlGroup": "GitGutterDelete",
  "git.topRemovedSign.hlGroup": "GitGutterDelete",
  "git.changeRemovedSign.hlGroup": "GitGutterChangeDelete",
  "tslint.autoFixOnSave": true,
  "eslint.packageManager": "yarn",
  "eslint.autoFixOnSave": true,
  "eslint.autoFix": true,
  "python.autoComplete.addBrackets": true,
  "python.jediEnabled": false,
  "html.format.enable": true,
  "javascript.referencesCodeLens.enable": false,
  "javascript.showUnused": true,
  "javascript.suggest.names": true,
  "javascript.suggestionActions.enabled": true,
  "javascript.format.enabled": true,
  "snippets.autoTrigger": true,
  "json.format.enable": true,
  "zi.enable": true,
  "zi.patterns": {
    "": [],
    "javascript": ["^\\s*\\/\\/", "^\\s*\\/\\*", "^\\s*\\*"],
    "typescript": ["^\\s*\\/\\/", "^\\s*\\/\\*", "^\\s*\\*"],
    "markdown": [],
    "vim": ["^\\s*\\\""],
    "gitcommit": []
  },
  "zi.syntaxKinds.javascript": [
    "StringLiteral",
    "NoSubstitutionTemplateLiteral",
    "TemplateHead",
    "TemplateTail",
    "TemplateMiddle"
  ],
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod"],
      "filetypes": ["go"],
      "initializationOptions": {
        "gocodeCompletionEnabled": true,
        "diagnosticsEnabled": true,
        "lintTool": "golint"
      }
    },
    "bash": {
      "command": "bash-language-server",
      "args": ["start"],
      "filetypes": ["sh"],
      "ignoredRootPaths": []
    },
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
      "rootPatterns": [".ccls-root", "compile_commands.json"],
      "initializationOptions": {
        "cache": {
          "directory": ".ccls-cache"
        }
      }
    }
  },
  "snippets.textmateSnippetsRoots": []
}
```

Thank you.

**Comment by chemzqm** [comment] 2020-02-24 03:01
Please upload log from `:CocOpenLog`

**Comment by Innei** [comment] 2020-02-24 04:39
```
2020-02-24T12:38:53.977 INFO (pid:22059) [services] - registered service "languageserver.golang"
2020-02-24T12:38:53.979 INFO (pid:22059) [services] - registered service "languageserver.bash"
2020-02-24T12:38:53.980 INFO (pid:22059) [services] - registered service "languageserver.ccls"
2020-02-24T12:38:54.017 INFO (pid:22059) [services] - registered service "eslint"
2020-02-24T12:38:54.232 INFO (pid:22059) [services] - registered service "highlight"
2020-02-24T12:38:54.607 INFO (pid:22059) [language-client-index] - highlight started with 22114
2020-02-24T12:38:54.635 INFO (pid:22059) [plugin] - coc 0.0.74-c57062d0da initialized with node: v13.5.0
2020-02-24T12:38:54.684 INFO (pid:22059) [services] - highlight server state change: starting => running
2020-02-24T12:38:57.682 ERROR (pid:22059) [events] - Error on InsertEnter:  Error: request error nvim_buf_clear_namespace - Invalid buffer id
    at /Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:14222:32
    at NvimTransport.parseMessage (/Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:10826:17)
    at DecodeStream.<anonymous> (/Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:10796:18)
    at DecodeStream.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at DecodeStream.Readable.push (_stream_readable.js:250:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:13746:12)
    at DecodeBuffer.flush (/Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:12736:12)
2020-02-24T12:39:00.846 ERROR (pid:22059) [events] - Error on InsertEnter:  Error: request error nvim_buf_clear_namespace - Invalid buffer id
    at /Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:14222:32
    at NvimTransport.parseMessage (/Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:10826:17)
    at DecodeStream.<anonymous> (/Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:10796:18)
    at DecodeStream.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at DecodeStream.Readable.push (_stream_readable.js:250:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:13746:12)
    at DecodeBuffer.flush (/Users/innei/.config/nvim/plugged/coc.nvim/build/index.js:12736:12)

```

**Comment by chemzqm** [comment] 2020-02-24 06:42
Can't reproduce.

**Comment by Innei** [comment] 2020-02-24 09:26
Maybe it conflicts with other plugins.

My nvim config here, if you have time to troubleshoot, thank you.

ps: I sat  git.addGBlameToVirtualText = false to ingore error.
<https://github.com/Innei/nvim>

**Comment by chemzqm** [comment] 2020-02-27 11:56
Fixed on latest release branch of coc.nvim.

**Closed as completed by chemzqm** 2020-02-27 11:56 UTC
Labels: question
