### ISSUE TITLE
[coc.nvim]: UnhandledRejection: Error: Failed to execute git

### ISSUE THREAD

**Issue by isvicy** [neoclide/coc-git#128] opened 2020-07-25 17:15 UTC
when edit file that is soft linked to a file in a git repo, got this "[coc.nvim]: UnhandledRejection: Error: Failed to execute git" error。 All works fine in other cases.

Just want to know how can I bypass this annoying reminder ?

**Comment by sainnhe** [comment] 2020-07-30 10:01
Same issue here, I found that this bug is caused by commit e360bcf8

Any chance to fix this? @chemzqm @fannheyward 

## Result from CocInfo

```log
## versions

vim version: NVIM v0.5.0-615-g5f5bd576e
node version: v14.6.0
coc.nvim version: 0.0.78
coc.nvim directory: /home/sainnhe/.local/share/nvim/plugins/coc.nvim
term: tmux
platform: linux

## Output channel: explorer


## Output channel: snippets

[Info 5:42:12 PM] Using ultisnips directories: UltiSnips /home/sainnhe/.local/share/nvim/snippets
[Info 5:42:13 PM] Using ultisnips python command: pyx

## Output channel: translator


## Output channel: languageserver.pylance

[Info  - 5:42:12 PM] Pylance language server 2020.7.4 (pyright a65343ef) starting
[Info  - 5:42:13 PM] Server root directory: /opt/pylance-language-server/server
[Error  - 5:42:13 PM] Error reading settings: TypeError: Cannot read property 'replace' of undefined
[Info  - 5:42:13 PM] No configuration file found.
[Error  - 5:42:13 PM] stubPath /home/sainnhe/playground/typings is not a valid directory.
[Info  - 5:42:13 PM] Assuming Python platform Linux
[Error  - 5:42:13 PM] Exception caught when installing fs watcher for:
 /usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/sainnhe/.local/lib/python3.8/site-packages
/usr/lib/python3.8/site-packages
[Info  - 5:42:13 PM] Searching for source files
[Info  - 5:42:13 PM] Found 2 source files

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/sainnhe/playground
> git ls-files -- test.py
> git ls-files test.py
fatal: .git/index: index file open failed: Permission denied

Error 128 on: 'git ls-files -- test.py' in /home/sainnhe/playground
fatal: .git/index: index file open failed: Permission denied
Error: Failed to execute git
    at Git.<anonymous> (/home/sainnhe/.local/share/nvim/plugins/coc-git/lib/index.js:21732:39)
    at Generator.next (<anonymous>)
    at fulfilled (/home/sainnhe/.local/share/nvim/plugins/coc-git/lib/index.js:21645:58)resolved root: /home/sainnhe/playground
> git symbolic-ref --short HEAD
fatal: .git/index: index file open failed: Permission denied

Error 128 on: 'git ls-files test.py' in /home/sainnhe/playground
fatal: .git/index: index file open failed: Permission denied
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
fatal: .git/index: index file open failed: Permission denied

Error 128 on: 'git diff --staged --name-status' in /home/sainnhe/playground
fatal: .git/index: index file open failed: Permission denied
Error on git status
Failed to execute gitfatal: .git/index: index file open failed: Permission denied

Error 128 on: 'git diff --name-status' in /home/sainnhe/playground
fatal: .git/index: index file open failed: Permission denied
resolved root: /home/sainnhe/playground
> git ls-files -- test.py
> git ls-files test.py
fatal: .git/index: index file open failed: Permission denied

Error 128 on: 'git ls-files -- test.py' in /home/sainnhe/playground
fatal: .git/index: index file open failed: Permission denied
Error: Failed to execute git
    at Git.<anonymous> (/home/sainnhe/.local/share/nvim/plugins/coc-git/lib/index.js:21732:39)
    at Generator.next (<anonymous>)
    at fulfilled (/home/sainnhe/.local/share/nvim/plugins/coc-git/lib/index.js:21645:58)fatal: .git/index: index file open failed: Permission denied

Error 128 on: 'git ls-files test.py' in /home/sainnhe/playground
fatal: .git/index: index file open failed: Permission denied

## Output channel: highlight

[Info  - 5:42:13 PM] Highlight server running in node v14.6.0
```

## Describe the bug

See above.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create a git repo: `mkdir test && cd test && git init`
- Create a soft link: `touch test.py && ln -s /home/sainnhe/repo/test/test.py ./ln.py`
- Create file `mini.vim` with：

  ```vim
  call plug#begin('~/.local/share/nvim/plugins')
  Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
  Plug 'neoclide/coc-git', {'do': 'yarn install --frozen-lockfile'}
  call plug#end()
  ```

- Start (neo)vim with command: `nvim -u mini.vim /path/to/ln.py`
- Insert some characters that can change git status.
- Error appeared: `[coc.nvim]: UnhandledRejection: Error: Failed to execute git`

## Screenshots (optional)

If applicable, add screenshots to help explain your problem.

**Comment by chemzqm** [comment] 2020-09-11 09:16
Should be fixed.

**Closed as completed by chemzqm** 2020-09-11 09:16 UTC
